name: CI with Trivy, CodeQL and ECR Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write
  id-token: write

env:
  ECR_REPOSITORY: my-app  # PushするECRリポジトリ名
  IMAGE_TAG: latest

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v4

    - name: AWS 認証情報を設定
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: ECR にログイン
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Docker イメージをビルド
      run: |
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
        docker tag $ECR_REPOSITORY:$IMAGE_TAG \
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Trivy によるスキャン
      uses: aquasecurity/trivy-action@0.30.0
      with:
        image-ref: ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
        format: table
        exit-code: 0
        severity: CRITICAL,HIGH

    - name: Docker イメージを ECR に Push
      run: |
        docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Jenkins デプロイジョブをトリガ
      if: github.ref == 'refs/heads/main'
      env:
        JENKINS_URL: http://54.238.217.219:8080/job/deploy-my-app/build
        JENKINS_TOKEN: ${{ secrets.JENKINS_TRIGGER_TOKEN }}
        JENKINS_USER: ${{ secrets.JENKINS_USER }}
        JENKINS_PASS: ${{ secrets.JENKINS_PASS }}
      run: |
        curl -X POST --user "$JENKINS_USER:$JENKINS_PASS" "$JENKINS_URL?token=$JENKINS_TOKEN"

  codeql:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ]

    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v4

    - name: CodeQL セットアップ
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

    - name: CodeQL ビルド（Python）
      uses: github/codeql-action/autobuild@v2

    - name: CodeQL 解析実行
      uses: github/codeql-action/analyze@v2
